spring:
  application:
    name: jobfair
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
