-- Audit triggers for NBPT2 schema
-- Goal: log INSERT/UPDATE/DELETE operations into shared table NBP.NBP_LOG
--
-- Expected NBP.NBP_LOG columns:
--   ID, ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER
--
-- NOTE:
-- - This script assumes you can INSERT into NBP.NBP_LOG.
-- - If you get ORA-00942 / ORA-01031, ask DBA/owner to grant:
--     GRANT INSERT ON NBP.NBP_LOG TO NBPT2;
--   If NBP.NBP_LOG requires an explicit ID and has no default/trigger,
--   you'll also need access to the sequence used for ID generation.

-- Quick verification (run manually after executing this script):
--   1) Perform a DML statement, e.g.:
--        UPDATE NBPT2.MEDIA_OUTLETS SET updated_at = SYSTIMESTAMP WHERE 1 = 0;
--      (or any harmless update/insert/delete you can roll back)
--   2) Check the last log rows:
--        SELECT *
--        FROM NBP.NBP_LOG
--        ORDER BY DATE_TIME DESC
--        FETCH FIRST 20 ROWS ONLY;
--
-- Common errors:
-- - ORA-01031: insufficient privileges
--     -> need GRANT INSERT ON NBP.NBP_LOG TO NBPT2
-- - ORA-00942: table or view does not exist
--     -> either no privilege OR wrong schema name
-- - ORA-01400: cannot insert NULL into (NBP.NBP_LOG.ID)
--     -> NBP.NBP_LOG.ID has no default/identity/trigger; you'll need to set ID via sequence
--        (ask which sequence to use, or DBA to create a trigger/default)

-- Helper procedure (keeps trigger bodies tiny)
CREATE OR REPLACE PROCEDURE NBPT2.LOG_TO_NBP_LOG(
  p_action_name IN VARCHAR2,
  p_table_name  IN VARCHAR2
) AS
BEGIN
  -- Prefer not to set ID here; many designs have an IDENTITY/default or a trigger on NBP.NBP_LOG.
  INSERT INTO NBP.NBP_LOG (ACTION_NAME, TABLE_NAME, DATE_TIME, DB_USER)
  VALUES (
    p_action_name,
    p_table_name,
    SYSTIMESTAMP,
    SYS_CONTEXT('USERENV', 'SESSION_USER')
  );
END;
/

-- Template used below:
-- CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_<TABLE>
-- AFTER INSERT OR UPDATE OR DELETE ON NBPT2.<TABLE>
-- BEGIN
--   IF INSERTING THEN
--     NBPT2.LOG_TO_NBP_LOG('INSERT', '<TABLE>');
--   ELSIF UPDATING THEN
--     NBPT2.LOG_TO_NBP_LOG('UPDATE', '<TABLE>');
--   ELSIF DELETING THEN
--     NBPT2.LOG_TO_NBP_LOG('DELETE', '<TABLE>');
--   END IF;
-- END;
-- /

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_MEDIA
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.MEDIA
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'MEDIA');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'MEDIA');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'MEDIA');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_STAT_BOARDS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.STAT_BOARDS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'STAT_BOARDS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'STAT_BOARDS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'STAT_BOARDS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_STATS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.STATS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'STATS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'STATS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'STATS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_PEOPLE
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.PEOPLE
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'PEOPLE');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'PEOPLE');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'PEOPLE');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_COMMITTEES
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.COMMITTEES
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'COMMITTEES');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'COMMITTEES');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'COMMITTEES');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_COMMITTEE_MEMBERS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.COMMITTEE_MEMBERS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'COMMITTEE_MEMBERS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'COMMITTEE_MEMBERS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'COMMITTEE_MEMBERS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_ORGANIZATIONS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.ORGANIZATIONS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'ORGANIZATIONS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'ORGANIZATIONS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'ORGANIZATIONS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_GALLERY_IMAGES
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.GALLERY_IMAGES
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'GALLERY_IMAGES');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'GALLERY_IMAGES');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'GALLERY_IMAGES');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_PACKAGE_TIERS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.PACKAGE_TIERS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'PACKAGE_TIERS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'PACKAGE_TIERS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'PACKAGE_TIERS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_PARTICIPATIONS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.PARTICIPATIONS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'PARTICIPATIONS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'PARTICIPATIONS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'PARTICIPATIONS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_ARTICLES
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.ARTICLES
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'ARTICLES');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'ARTICLES');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'ARTICLES');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_ARTICLE_IMAGES
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.ARTICLE_IMAGES
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'ARTICLE_IMAGES');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'ARTICLE_IMAGES');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'ARTICLE_IMAGES');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_JOBS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.JOBS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'JOBS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'JOBS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'JOBS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_JOB_TAGS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.JOB_TAGS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'JOB_TAGS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'JOB_TAGS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'JOB_TAGS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_MEDIA_OUTLETS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.MEDIA_OUTLETS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'MEDIA_OUTLETS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'MEDIA_OUTLETS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'MEDIA_OUTLETS');
  END IF;
END;
/

CREATE OR REPLACE TRIGGER NBPT2.TRG_NBP_LOG_MEDIA_PARTICIPATIONS
AFTER INSERT OR UPDATE OR DELETE ON NBPT2.MEDIA_PARTICIPATIONS
BEGIN
  IF INSERTING THEN
    NBPT2.LOG_TO_NBP_LOG('INSERT', 'MEDIA_PARTICIPATIONS');
  ELSIF UPDATING THEN
    NBPT2.LOG_TO_NBP_LOG('UPDATE', 'MEDIA_PARTICIPATIONS');
  ELSIF DELETING THEN
    NBPT2.LOG_TO_NBP_LOG('DELETE', 'MEDIA_PARTICIPATIONS');
  END IF;
END;
/
